name: build design tokens

on:
  pull_request:
    paths:
      - "tokens.json"
      - ".github/workflows/build.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: "16.x"
          registry-url: https://npm.pkg.github.com/

      - name: install node_modules
        run: yarn

      - name: build tokens
        run: yarn token

      - name: get pull request number
        run: echo pr_number=$(echo $GITHUB_REF | sed -e 's/[^0-9]//g') >> $GITHUB_OUTPUT
        id: pr_number

      - name: commit built tokens
        id: "auto-commit-action"
        uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a # v4
        with:
          commit_message: "Update design tokens #${{ steps.pr_number.outputs.pr_number }}"
