name: publish design tokens

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/publish.yml"
      - "src/tokens/**"
      - "package.json"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: "16.x"
          registry-url: https://npm.pkg.github.com/

      - name: set version to env
        run: node -p -e '`VERSION=${require("./package.json").version}`' >> $GITHUB_ENV
      - run: npm ci
      - name: publish to npm
        run: |
          CURRENT_VERSION=$(npm view @ninout-ai/design-tokens version)
          EXISTING_VERSION=${{ env.VERSION }}
          if [ "$CURRENT_VERSION" != "$EXISTING_VERSION" ]; then
            echo "Current version ($CURRENT_VERSION) does not match existing version ($EXISTING_VERSION), publishing package..."
            npm publish
          else
            echo "Current version ($CURRENT_VERSION) already exists, skipping publish..."
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: add version tag
        uses: pkgdeps/git-tag-action@00821b688297ad5792cf50e6aaa0d4404bec49d0 # v2
        with:
          version: ${{ env.VERSION }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: "v"
